name: Apply ClusterResourceSet ApplyAlways Strategy Patches

on:
  push:
    branches:
      - release/**

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out patch branch
      uses: actions/checkout@v3
      with:
        path: 'patches'
        repository: 'mesosphere/cluster-api'
        ref: 'crs-strategy-applyalways'
    - name: Check out target branch
      uses: actions/checkout@v3
      with:
        path: 'cluster-api'
    - name: Apply patches
      run: |
        git apply \
          patches/*.patch \
          --directory cluster-api
    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        path: 'cluster-api'
        commit-message: "feat: Add ClusterResourceSet ApplyAlways Strategy"